# Generated by Django 2.1.5 on 2019-01-27 11:37

from django.db import migrations, models
import useraccount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('college', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('sem', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
            },
            managers=[
                ('objects', useraccount.models.UserManager()),
            ],
        ),
    ]
